language: node_js

node_js: 
  - '6'

addons:
  sonarcloud: true

script:
  - npm build
  - npm test
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=SyTW12018 -Dsonar.projectKey=E06 -Dsonar.sources='E06/server' -X