dist: trusty
language: node_js

node_js: 
  - '6'

addons:
  sonarcloud:
    organization: "sytw12018"
    token:
      secure: SGbamgCznXqzN+XDB8EaLlV60BLpD3KLGwSEP8wKT6Imt6isM0Q1sMxOaOjkMUjdykoNLLz6bOEPcVJstm5/+I5iJfO4mQIjU62byRihDv41f4Q6rnhXv0wCg7lVVeKHQhfVWkkKAD6VGqfUBxz1iaeBv/hoVnCHTIr01QopGyz06xCeORQBcZjHAX6FkXeWsyIKSoahTb59jWjcqDn7NMQKGCReDrzv6a1mauKoJmHette57uNJVDT0CjW2fODYQI6tYz8JubOHefbby9DvcOlo/tZy7UxeOYuZrlzvTehB8ipCVWHlcAXZ35sYxA7jaxAZrSWypcKI6/w+MzIDQRUJ/7lO8HdWJ3Q6PxHIhMhxhH1SJTwwB6J1uovp9F6gZ91JNcK+g4EhuRNYc+PwhIyzSDZIcqUlYb131bbE8fq8QH8Q6/XIaZSQK+/O+GpnLRoC7yAR0t03MsuVocgjS5/mbuzBOo8IvO8r7qmAPWpdKtW1jaZTSPbL6lNkYkkIqQ4dHplTFC6Iv+qD1cV/vgvwORQP2pUeliPAxS2MC1bFggqY/0Aye8IuliuuAu64yp4GUgjiqQcHTjsjsPScN8q6Wq3uoyCfWqrHySjtFAFVzMZxhFgHC4mQ/j0hBMvdHKs/XuPfwyXxTVNchycOTRpX73+gWpYSa/LmFRDgW/k=

script:
  - npm build
  - npm test
  - sonar-scanner

services: mongodb

notifications:
    on_success: always
    slack: 
      rooms:
        secure: "Y2umfVS2tPmJmXVesE/rGtWyH+DhzhH33C1aFpk/nvmhmfo5FkWQRSjF0HoZwm4xaVZpiNqGXsJ6YaYxMq1u/85iE/aehMuoXj3zdvPV/f08jp1Fzh0XdA46NPhxvIofmHfeGbr3ylPSxX5n5JkzpDVeS7Ej7Sr5j1F7ISSuERs/as3vp1Xg4B+bj6S8zBoY/HMGaXiY3cH5wO6ycWjmRLArIPySW12ahW8qiR1tsWWCE+Iuaw83wfuV/Qn1tc0eah+Ao2S4o01Dci2aFSTPu3GL/p+Xjnbna+H93Pk5j8nEfaVIjKwhnHX3M2sWAMDLl+bbxPQLFnjTdtDqpLyDNGkQr8dZOJxDOTkINLel3R0HZhCcRy5zmY6yJ1VjYK7GEsuCzTHg8lMDnri6v3LqI1mSxkdIxtetNn71bKjHtYTHggglcdoCheTlRWwBwSE8VOR7lj4qeJMquoD8cGj6BOTuiBLBVbnCoQqndRgkQaV+ZNUoMd7Vm2/iMYf3M/vwpYiNlX6xd6Wq6DP76e0YszzXZ+p6ylsQ6jiy0aG0pIvQJ0yQcUHJZIoeDTJjAZ+FTzGWWQtDn/zS8xPO46Sw3skjg+ahkoV+wnpa+n9X+huyXmiO8DGzX1HRU5tM8j6drBkvRqQ1WxqzUjo+h6Rr3laTrxhIpSSJsWRECr4Rhwg="
