dist: trusty
language: node_js

node_js: 
  - '6'

addons:
  sonarcloud:
    organization: "sytw12018"
    token:
      secure: "**************************" # encrypted value of your token

script:
  - npm build
  - npm test

services: mongodb


notifications:
  slack:
    rooms: sytw:V3U1QY6Dyevgv3Er9YEkxMO6#e06 
    on_success: always

