# sudo: false
# language: node_js
# nodejs:
#   - node

# before_install:
#   - npm i

# cache: npm

# install:
#   - npm ci

# script: 
#   - npm test

language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"